# Generated by Django 3.2.4 on 2021-06-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca del Vehiculo')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo del Vehiculo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopapp.categoria')),
            ],
        ),
    ]
