# Generated by Django 3.2.4 on 2021-06-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('nombreMascota', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='nombre Mascota')),
                ('nombreDueño', models.CharField(max_length=20, verbose_name='nombre Dueño')),
                ('raza', models.CharField(max_length=20, verbose_name='raza')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('idTipoMascota', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de TipoMascota')),
                ('nombreTipoMascota', models.CharField(max_length=50, verbose_name='Nombre TipoMascota')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.AddField(
            model_name='mascota',
            name='TipoMascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopapp.tipomascota'),
        ),
    ]
