# Generated by Django 3.2.4 on 2021-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0003_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=60, max_length=3, verbose_name='edad'),
            preserve_default=False,
        ),
    ]
