# Generated by Django 3.2.4 on 2021-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='comuna',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='telefono',
            field=models.CharField(max_length=10, null=True, verbose_name='telefono'),
        ),
    ]
