# Generated by Django 3.2.4 on 2021-06-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0009_auto_20210621_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='telefono',
        ),
    ]
